
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "i", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[terminal]
